### ISSUE TITLE
NullPointerException report when validating an HTML5

### ISSUE THREAD

**Issue by octavianN** [validator/validator#1057]
Error reported by an user when validating an HTML5 document.
It looks like a RuntimeException thrown through StyleSheetParser, which when caught, does not have variable initialized.
We don't have a way to reproduce yet.
```
java.lang.NullPointerException
    at org.w3c.css.css.StyleSheetParser.parseStyleElement(StyleSheetParser.java:350)
    at org.w3c.css.css.StyleSheetParser.parseStyleSheet(StyleSheetParser.java:412)
    at nu.validator.checker.schematronequiv.Assertions.endElement(Assertions.java:1467)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at com.thaiopensource.xml.sax.ForkContentHandler.endElement(Unknown Source)
    at nu.validator.xml.CombineContentHandler.endElement(CombineContentHandler.java:81)
    at nu.validator.htmlparser.sax.SAXStreamer.elementPopped(SAXStreamer.java:138)
    at nu.validator.htmlparser.sax.SAXStreamer.elementPopped(SAXStreamer.java:35)
    at nu.validator.htmlparser.impl.TreeBuilder.pop(TreeBuilder.java:4761)
    at nu.validator.htmlparser.impl.TreeBuilder.endTag(TreeBuilder.java:3960)
    at nu.validator.htmlparser.impl.Tokenizer.emitCurrentTagToken(Tokenizer.java:1152)
    at nu.validator.htmlparser.impl.Tokenizer.stateLoop(Tokenizer.java:3851)
    at nu.validator.htmlparser.impl.Tokenizer.tokenizeBuffer(Tokenizer.java:1415)
    at nu.validator.htmlparser.io.Driver.runStates(Driver.java:303)
    at nu.validator.htmlparser.io.Driver.tokenize(Driver.java:216)
    at nu.validator.htmlparser.sax.HtmlParser.tokenize(HtmlParser.java:480)
    at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:423)
```

**Comment by j9t** [comment]
What have you been validating? Do you have an example URL or the respective HTML code that allows to reproduce?

**Comment by j9t** [comment]
@octavianN, I’m feeling free to close this one. Please follow up with details so to be able to reproduce the issue. Thanks!
