### ISSUE TITLE
Unencoded ampersand triggers AssertionError: strBufLen not reset after previous use!

### ISSUE THREAD

**Issue by sbeimin** [validator/validator#1273]
The following html triggers a bug in the tokenizer:

`<!DOCTYPE html><html><head><title></title></head><body><div>&abc</div></body></html>`

You'd expect this to cause a validation error. Instead it triggers a bug in the tokenizer.

**Comment by sbeimin** [comment]
```
@Test
public void testUnencodedAmpersand() throws SAXException, SchemaReadException, Exception {
	String html = "<!DOCTYPE html><html><head><title></title></head><body><div>&abc</div></body></html>";
	try (InputStream is = new ByteArrayInputStream(html.getBytes())) {
		SimpleDocumentValidator validator = new SimpleDocumentValidator();
		ErrorHandler errorHandler = new DefaultHandler();
		validator.setUpMainSchema(EmbeddedValidator.SCHEMA_URL, errorHandler);
		validator.setUpValidatorAndParsers(errorHandler, false, false);
		validator.checkHtmlInputSource(new InputSource(is));
	}
}
```

**Comment by sideshowbarker** [comment]
> The following html triggers a bug in the tokenizer:
> 
> `<!DOCTYPE html><html><head><title></title></head><body><div>&abc</div></body></html>`
> 
> You'd expect this to cause a validation error.

I think per the current spec, `<div>&abc</div>` is actually not a conformance error. In older versions of the spec, it was — but that subsequently changed.

> Instead it triggers a bug in the tokenizer.

I can’t reproduce that when I test with the checker (validator) itself. The running code throws no exceptions.

**Comment by sbeimin** [comment]
I was using the following dependency:
```
<dependency>
	<groupId>nu.validator</groupId>
	<artifactId>validator</artifactId>
	<version>20.7.2</version>
	<scope>test</scope>
</dependency>
```
Did you run the test with -ae (assertions enabled)?

**Comment by sideshowbarker** [comment]
> I was using the following dependency:
> 
> ```
> <dependency>
> 	<groupId>nu.validator</groupId>
> 	<artifactId>validator</artifactId>
> 	<version>20.7.2</version>
> 	<scope>test</scope>
> </dependency>
> ```

Yeah, that’s not up to date with the latest changes. But I’ve not yet released new Maven packages that have the changes which got made after that release.

> Did you run the test with -ae (assertions enabled)?

No, I haven’t tested with running it from Java code using the `SimpleDocumentValidator` API. I’m just testing with the checker itself — both running as a web service, and using the `vnu.jar` fat jar from the command line:

```bash
$ echo '<!DOCTYPE html><html><head><title></title></head><body><div>&abc</div></body></html>' \
     | java -jar ./build/dist/vnu.jar -
:1.35-1.42: error: Element “title” must not be empty.
:1.16-1.21: info warning: Consider adding a “lang” attribute to the “html” start tag to declare the language of this document.
```

**Comment by sbeimin** [comment]
```
$ echo '<!DOCTYPE html><html><head><title></title></head><body><div>&abc</div></body></html>' | java -ea -jar vnu.jar -
Exception in thread "main" java.lang.AssertionError: strBufLen not reset after previous use!
	at nu.validator.htmlparser.impl.Tokenizer.clearStrBufBeforeUse(Tokenizer.java:940)
	at nu.validator.htmlparser.impl.Tokenizer.stateLoop(Tokenizer.java:3847)
	at nu.validator.htmlparser.impl.Tokenizer.tokenizeBuffer(Tokenizer.java:1429)
	at nu.validator.htmlparser.io.Driver.runStates(Driver.java:302)
	at nu.validator.htmlparser.io.Driver.tokenize(Driver.java:219)
	at nu.validator.htmlparser.sax.HtmlParser.tokenize(HtmlParser.java:488)
	at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:408)
	at nu.validator.xml.WiretapXMLReaderWrapper.parse(WiretapXMLReaderWrapper.java:158)
	at nu.validator.validation.SimpleDocumentValidator.checkAsHTML(SimpleDocumentValidator.java:532)
	at nu.validator.validation.SimpleDocumentValidator.checkHtmlInputSource(SimpleDocumentValidator.java:405)
	at nu.validator.client.SimpleCommandLineValidator.main(SimpleCommandLineValidator.java:309)
```

**Comment by sideshowbarker** [comment]
Can’t reproduce now, so apparently this was subsequently fixed by some intervening HTML parser changes.
