### ISSUE TITLE
Shading the forked/vendored version of Jing that the validator relies on

### ISSUE THREAD

**Issue by oliviercailloux** [validator/validator#1504]
**Is your feature request related to a problem? Please describe.**
The [`nu.validator:jing:20200702VNU`](https://search.maven.org/artifact/nu.validator/jing) version [listed](https://search.maven.org/artifact/nu.validator/validator/20.7.2/jar) as a dependency of the `nu.validator:validator` Maven artifact differs from both the latest (20220510) and the previous (20181222) [`org.relaxng:jing`](https://search.maven.org/artifact/org.relaxng/jing) version.

**Describe the solution you'd like**
Please consider updating the dependency to jing to the latest version.

**Describe alternatives you've considered**
Please consider alternatively documenting whether one can use `org.relaxng:jing:20220510` instead of `nu.validator:jing:20200702VNU` with no risk. For example, both versions contain a `com.thaiopensource.validate.SchemaReader` class, but I ignore whether they are identical.

**Comment by oliviercailloux** [comment]
I hope that it is not inappropriate to bump this thread, hoping for some light about the possibility of using a recent version of Jing together with Nu validator. 

This would allow for using Nu validator as a library using reasonably clean code (as the 2022 version of Jing has a much improved approach to validation).

Is there a plan of updating the Jing dependency in Nu? That would be the cleanest approach. Otherwise, would you consider at least shading the Nu-specific version of Jing that currently comes as a dependency? It would follow best practices to not shadow classes that may appear elsewhere in a project, as this creates a nightmare for developers down the road when it appears that some classes conflict.

**Comment by oliviercailloux** [comment]
As an end of year gift, jing has released a small update ([removed dependency](https://github.com/relaxng/jing-trang/issues/280) on old apis, mostly).

If anybody can find some time to answer this thread about the dependency to an older version of jing, I still think that it would be of much added value for people trying to embed Nu validator in other libraries.

**Comment by sideshowbarker** [comment]
> Otherwise, would you consider at least shading the Nu-specific version of Jing that currently comes as a dependency?

I am not sure what you mean by “shading”. But if you mean, could we release a Maven package with the vnu-specific version of Jing bundled/packaged/build directly into the vnu.jar, then yes, I think is possible.

Is that what you’d like for me to do?

https://github.com/validator/validator/blob/main/build/build.xml is our build file. The target name for the jar asset that’s in Maven releases is `validator-jar` (the target named just `jar` is the full fat jar that contains all the dependencies).

That `validator-jar` target currently just looks like this:

```xml
  <target name="validator-jar" depends="validator-build">
    <mkdir dir="${validator.basedir}/jars"/>
    <jar destfile="${jarsDir}/validator.jar" basedir="${validator.build.basedir}/full/classes" excludes="**/*.java">
      <fileset dir="${validator.build.basedir}/resources"/>
    </jar>
  </target>
```

But to make it include/bundle the vnu-specific Jing, I can do this:

```xml
  <target name="validator-jar" depends="validator-build, jing-build">
    <mkdir dir="${validator.basedir}/jars"/>
    <jar destfile="${jarsDir}/validator.jar" basedir="${validator.build.basedir}/full/classes" excludes="**/*.java">
      <fileset dir="${validator.build.basedir}/resources"/>
    </jar>
    <zipfileset src="jing-trang/build/jing.jar" unless:true="${jar-without-deps}"/>
  </target>
```
…and of course, in addition to the above, also change the POM file, to remove this:

```xml
      <dependency groupId="nu.validator" artifactId="jing" version="20200702VNU"/>
```

I’ve tried building with that locally, and it all works. But I’m not certain the resulting jar would be what you want.

So, can you confirm whether a jar (Maven asset) built in that way would work for you?

If not — if there’s some other way I’d need to build it — then would need your help in updating our build to make that happen.

Or better yet, I would be happy to have a patch/PR for it.

So, please let me know how you’d like to proceed here.

**Comment by sideshowbarker** [comment]
To answer your other specific questions:

> Is there a plan of updating the Jing dependency in Nu? 

No, there is not.

> Please consider alternatively documenting whether one can use `org.relaxng:jing:20220510` instead of `nu.validator:jing:20200702VNU` with no risk.

If you want to use Jing with the validator code, you can’t use `org.relaxng:jing:20220510`.

Otherwise, I guess you can use `org.relaxng:jing:20220510` for whatever other purposes you might want to.

> This would allow for using Nu validator as a library using reasonably clean code (as the 2022 version of Jing has a much improved approach to validation).

The validator is tightly bound (and will remain so) to the separate vnu-specific version of Jing. So I guess that if you want to use whatever different approach to validation is provided by the non-vnu version of Jing, you will not be able to use Nu validator as part of that. As far as I understand, it’s an either-or.

**Comment by sideshowbarker** [comment]
The jars published to Maven Central at https://repo1.maven.org/maven2/nu/validator/validator/ and at https://github.com/validator/validator/packages/892686 now bundle in Jing — as well as bundling in the validator.nu HTML parser.

Please test with those jars in your local maven environment — and if you find any problems, raise a bug in the issue tracker and/or post a comment to this issue.

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this for now. If there are any problems that come up with using the new Jing-classes-included Maven releases, it seems best to file new/separate issues for those.

**Comment by oliviercailloux** [comment]
I am sorry for my late reaction, and for the misunderstanding. I did not mean to integrate the dependency code inside the nu validator jar, for I do not think that this is good practice. It makes it more difficult for users of nu validator to know what code comes bundled when adding it as a dependency as it becomes non-transparent and unknown to the maven packaging system, whereas with explicit dependencies it is at least visible that by calling in nu validator, we also get the 2020 version of jing. So users of the previous version could hopefully see that they would meet possible difficulties if also relying on the 2022 version of jing.

Also, bundling in such a way solves no problem (unless something escaped me): the conflicting code is still there, it’s just less obvious that the conflict exists.

By shading the jing dependency I actually meant renaming its packages before including in in the nu jar, so as to avoid conflict with recent jing versions (which are different but have the same name). See [here](https://softwareengineering.stackexchange.com/questions/297276/what-is-a-shaded-java-dependency) for example.

I am aware that the internet generally warns about shading as a last resort option, and that is certainly an advice that I share. But in this case, with nu depending on an old version of jing, now incompatible with more recent versions, considering that the nice solution to this problem (depending on a recent version of jing and separating just the nu specific parts in non-name-conflicting classes) seems out of reach, it seems that only this “last resort” option remains.

Sorry again for not reacting on time and the trouble caused. Please tell me if I should open a new issue.

In any case, if you do not have time to think about this for now, please at least consider undoing the jar-integration that my issue unwantedly lead to.

**Comment by sideshowbarker** [comment]
> By shading the jing dependency I actually meant renaming its packages before including in in the nu jar, so as to avoid conflict with recent jing versions (which are different but have the same name). See [here](https://softwareengineering.stackexchange.com/questions/297276/what-is-a-shaded-java-dependency) for example.

OK, I understand now.

I am perfectly happy if we can get the build of the maven validator package updated such that our forked/vendored jing classes that are bundled in get shaded/relocated/renamed into the resulting packaged Maven assets.

But I’m certain you know much more about how to make a Maven package build do that than I do.

👉 **So, would you be able to submit a patch to the validator build sources that accomplishes the shading?**

We use ant (not Maven) to build the assets, and https://github.com/validator/validator/blob/main/build/build.xml is where you can find that source for the build file.

So I think the quickest way to get the change made to fix the conflict would be if you were able to modify the existing build to do that — and test it troubleshoot it and confirm that it all works — and then submit a PR here with a patch.

---

If you’re not able to do that, then I guess I can eventually try to make some time to do it myself. But please understand that:

- I am not a Maven user. At all.
- I don’t even have a local Maven environment in which I could test out that resulting package works Maven-wise.
- I know very little about how to properly do builds of Maven packages.
- The existing Maven build we have is just the result of me doing a lot of trial and error — over many many hours.

But all that said, I have read up a bit and found that there is a tool at https://code.google.com/archive/p/jarjar/ that I might be able to use to achieve the shading — and that it _may_ be as simple as just doing something somewhere like this:

```xml
<target name="shade">
  <taskdef name="jarjar"
           classname="com.tonicsystems.jarjar.JarJarTask"
           classpath="lib/jarjar-1.4.jar"/>
  <jarjar destfile="build/vnu-shaded.jar">
    <zipfileset src="build/vnu.jar"/>
    <rule pattern="com.thaiopensource.**" result="nu.validator.jingtrang.@1"/>
  </jarjar>
</target>
```

But who knows — I haven’t tried it yet, and I don’t how soon I might be able to set aside time to even try it.

What I can say is that, every time I have set out to do anything with the Maven-related stuff for the validator project, it has ended up costing me much, much more than I ever thought it would — hours and hours.

So that experience leads me to suspect that if I were to try myself to update the current build to do the shading, it’s going to take me a considerable amount of time — on the order of some number of hours — to attempt it and go through the repeated trial-and error of troubleshooting it.

However, I suspect that because you’re a Maven user and know infinitely more about this stuff than I do, it seems very likely that you might be able to get it figured out much more quickly than I could — and you do a PR with patch that enables it.

**Comment by oliviercailloux** [comment]
Thank you for your thoughtful reply.

This may already be clear, but I’ll spell it out briefly just to make sure we’re aligned: the problem at issue is unrelated to Maven, as I understand it. A user of Nu Validator using anything other than Maven as a build system will also encounter the difficulty that depending on Nu Validator requires the presence of the Jing version 20200702VNU JAR in the classpath (this is true irrespective of whether this dependency is brought automatically by Maven or by another packaging mechanism or downloaded manually and added to the classpath), and if that user also wishes to depend on Jing-more-recent-and-incompatible-version, she is currently stuck.

As a solution, I propose to shade this 20200702VNU version of Jing inside the JAR distributed by VNU. Again, this is independent of Maven. As you observe, tools probably exist to ease this process in Ant.

I do not know how to shade a JAR with Maven (I have fortunately not had to do this yet), and in any case, this would probably not help much in your case, as your build system is Ant. Also, the main difficulty with shading the JAR, I suspect, is checking that this shading process does not hurt the functionality of Nu Validator: it might be that this package renaming has an effect on the rest of the code. Knowing about which areas of the code are more likely to be affected requires knowledge of the code (in particular, whether any reflection is in place, I suppose), and is again independent of Maven as this is a pure Java coding problem.

You are probably right to expect that specific Maven testing will be useful, as the resulting JAR should advertise its dependencies correctly so as to fit into the Maven system. But, as I understand it, this should be the easy part: once your own version of Jing is shaded inside your own JAR, the resulting JAR simply does not depend on Jing anymore at all, from Maven’s point of view.

In any case, if you have questions about Maven use or best practices that I can answer in reasonable time, I will be most happy to be useful, and, independently, to test your resulting JAR as a Maven user.

**Comment by sideshowbarker** [comment]
To be clear: At this point, unless/until you or someone else contributes a patch which implements the shading you propose, and tests it and does everything else necessary to help ensure it's not broken anything else, I plan to do absolutely nothing about this myself.

**Comment by sideshowbarker** [comment]
OK, I’ve released version 25.12.24 of the Maven package — with all of the classes from our vendored jing-trang fork shaded.

For more details, see https://github.com/validator/validator/commit/5559f0af6a8957726fed668f0570bde833e8feb1. Please test it and lemme know if you run into any problems with it.

**Comment by boris-petrov** [comment]
@sideshowbarker I've been trying all releases since this change and I keep getting:

java.lang.NoClassDefFoundError: nu/validator/vendor/thaiopensource/validate/Schema

I'm using the Maven release.

Which is indeed true - there is no such file in the JAR file. I see `com.thaiopensource.validate.Schema.class`. So perhaps something hasn't been done right with the shading part, at least in the Maven release.

**Comment by sideshowbarker** [comment]
> [@sideshowbarker](https://github.com/sideshowbarker) I've been trying all releases since this change and I keep getting:
> 
> java.lang.NoClassDefFoundError: nu/validator/vendor/thaiopensource/validate/Schema
> 
> I'm using the Maven release.
> 
> Which is indeed true - there is no such file in the JAR file. I see `com.thaiopensource.validate.Schema.class`. So perhaps something hasn't been done right with the shading part, at least in the Maven release.

Yeah — please raise a new issue for that

**Comment by boris-petrov** [comment]
[Done](https://github.com/validator/validator/issues/2008)!

**Comment by oliviercailloux** [comment]
> Please test it and lemme know if you run into any problems with it.

Thanks a lot! Here is a possible problem.

```java
    final Path html = Path.of(getClass().getResource("Xhtml/Simple.xhtml").toURI());
    final EmbeddedValidator validator = new EmbeddedValidator();
    validator.setOutputFormat(EmbeddedValidator.OutputFormat.GNU);
    final String output = validator.validate(html);
```
yields:

```java
java.lang.NoSuchMethodError: 'boolean com.ibm.icu.lang.UCharacter.isHighSurrogate(char)'
 at nu.validator.htmlparser.extra.NormalizationChecker.characters(NormalizationChecker.java:166)
 at nu.validator.gnu.xml.aelfred2.XmlParser.readDataChunk(XmlParser.java:4505)
 at nu.validator.gnu.xml.aelfred2.XmlParser.fillBuffer(XmlParser.java:3675)
 at nu.validator.gnu.xml.aelfred2.XmlParser.readCh(XmlParser.java:3605)
 at nu.validator.gnu.xml.aelfred2.XmlParser.skipWhitespace(XmlParser.java:2626)
 at nu.validator.gnu.xml.aelfred2.XmlParser.parseMisc(XmlParser.java:1037)
 at nu.validator.gnu.xml.aelfred2.XmlParser.parseProlog(XmlParser.java:742)
 at nu.validator.gnu.xml.aelfred2.XmlParser.parseDocument(XmlParser.java:615)
 at nu.validator.gnu.xml.aelfred2.XmlParser.doParse(XmlParser.java:512)
 at nu.validator.gnu.xml.aelfred2.SAXDriver.parse(SAXDriver.java:436)
 at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:345)
 at nu.validator.xml.WiretapXMLReaderWrapper.parse(WiretapXMLReaderWrapper.java:158)
 at nu.validator.validation.SimpleDocumentValidator.checkAsXML(SimpleDocumentValidator.java:568)
 at nu.validator.validation.SimpleDocumentValidator.checkXmlFile(SimpleDocumentValidator.java:476)
 at nu.validator.client.EmbeddedValidator$OneOffValidator.validate(EmbeddedValidator.java:303)
 at nu.validator.client.EmbeddedValidator.validate(EmbeddedValidator.java:84)
 at io.github.oliviercailloux.jaris.xml.NuTests.testEmbeddedValidatorAccepts(NuTests.java:88)
```

Indeed, `nu.validator:validator:26.1.5` [depends](https://central.sonatype.com/artifact/nu.validator/validator/dependencies) on ICU4J 75.1, whose [UCharacter](https://javadoc.io/static/com.ibm.icu/icu4j/75.1/com/ibm/icu/lang/UCharacter.html) does not contain `isHighSurrogate(char)`.

**Comment by sideshowbarker** [comment]
Howdy Olivier

Thanks much for reporting that problem. It’s a great catch — something that had gone unnoticed despite the fact we added a bunch of tests recently to try to identify problems like that one.

Anyway, I have now added a test for it — along with making a fix for it, in https://github.com/validator/validator/commit/2dfb00a6ea

And, I’ve released a new Maven package, v26.1.7, containing that fix. So, please try it out, and if it doesn’t fix the problem — or if still has other problems — then please lemme know.

P.S. Despite the testiness of some of my earlier comments in this issue, I’m very grateful to you for your nudging about the original issue here. Your persistence has resulted in making the checker better in a number of ways than it would’ve been otherwise. So, thanks.

**Comment by oliviercailloux** [comment]
Thanks a lot for your reactivity and kind words. It now works when used in isolation. (I just stumbled upon another problem so I’ll open a new issue for this.)
