### ISSUE TITLE
Host is down build problem.

### ISSUE THREAD

**Issue by javajosh** [validator/validator#173]
Hello! I'm not sure what I'm doing wrong here, but I can't seem to build. It looks like a connectivity problem, but as you can see at the last command, I can `wget` just fine!

```bash
$ python --version
Python 2.7.10

$ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

# josh at emil in ~/proj [12:44:55]
$ git clone https://github.com/validator/validator.git
Cloning into 'validator'...
remote: Counting objects: 18057, done.
remote: Total 18057 (delta 0), reused 0 (delta 0), pack-reused 18057
Receiving objects: 100% (18057/18057), 8.85 MiB | 3.61 MiB/s, done.
Resolving deltas: 100% (10523/10523), done.
Checking connectivity... done.

# josh at emil in ~/proj [12:45:13]
$ cd validator

# josh at emil in ~/proj/validator on git:master o [12:45:20]
$ python ./build/build.py all
"git" submodule update --init
Submodule 'htmlparser' (https://github.com/validator/htmlparser.git) registered for path 'htmlparser'
Submodule 'jing-trang' (https://github.com/relaxng/jing-trang.git) registered for path 'jing-trang'
Submodule 'tests' (https://github.com/validator/tests.git) registered for path 'tests'
Cloning into 'htmlparser'...
remote: Counting objects: 8117, done.
remote: Total 8117 (delta 0), reused 0 (delta 0), pack-reused 8117
Receiving objects: 100% (8117/8117), 11.47 MiB | 4.13 MiB/s, done.
Resolving deltas: 100% (2422/2422), done.
Checking connectivity... done.
Submodule path 'htmlparser': checked out '543cc3e7d442874c10ed40e114317115bcff1ca5'
Cloning into 'jing-trang'...
remote: Counting objects: 24050, done.
remote: Total 24050 (delta 0), reused 0 (delta 0), pack-reused 24050
Receiving objects: 100% (24050/24050), 27.87 MiB | 4.72 MiB/s, done.
Resolving deltas: 100% (13152/13152), done.
Checking connectivity... done.
Submodule path 'jing-trang': checked out '35eb11b84a230ee4d7168f12f98a28bf40e940aa'
Cloning into 'tests'...
remote: Counting objects: 6104, done.
remote: Total 6104 (delta 0), reused 0 (delta 0), pack-reused 6104
Receiving objects: 100% (6104/6104), 1010.54 KiB | 801.00 KiB/s, done.
Resolving deltas: 100% (3110/3110), done.
Checking connectivity... done.
Submodule path 'tests': checked out '8c94105ba62f2eb20d1f938d2a98e62160a28c6a'
https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1.1/icu4j-54.1.1.jar
Traceback (most recent call last):
  File "./build/build.py", line 1438, in <module>
    downloadDependencies()
  File "./build/build.py", line 1171, in downloadDependencies
    downloadDependency(url, md5sum)
  File "./build/build.py", line 1162, in downloadDependency
    fetchUrlTo(url, path, md5sum)
  File "./build/build.py", line 1031, in fetchUrlTo
    f = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: < urlopen error [Errno 64] Host is down>

# josh at emil in ~/proj/validator on git:master o [12:45:37]
$ wget https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1.1/icu4j-54.1.1.jar
--2015-10-17 12:48:51--  https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1.1/icu4j-54.1.1.jar
Resolving repo1.maven.org... 23.235.47.209
Connecting to repo1.maven.org|23.235.47.209|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11126868 (11M) [application/java-archive]
Saving to: 'icu4j-54.1.1.jar'

icu4j-54.1.1.jar                  100%[==============================================================>]  10.61M  5.61MB/s   in 1.9s

2015-10-17 12:48:54 (5.61 MB/s) - 'icu4j-54.1.1.jar' saved [11126868/11126868]

**Comment by sideshowbarker** [comment]
I can’t reproduce this. I just tried a fresh clone and install from scratch, and the build completes without any errors. Can you please try it again and see if you get the same error? It may have just been a temporary Maven Central problem or some other network glitch.

**Comment by javajosh** [comment]
Good morning, and thanks for the fast response! I tried it again just now, same machine but from a different wifi access point, and same error...but then I got to thinking. What is unusual about my network setup? Am I running a proxy or something like that? And the answer was yes, I run Little Snitch, and it was silently dropping network traffic from python, which must have been a rule I installed to test out some potentially problematic code in the past.

Sorry. Closing.

**Comment by sideshowbarker** [comment]
> Sorry. Closing.

No worries. Your bug report is a good bug report in that it identifies a real problem. The fact that it turned out not be caused by the validator code doesn’t mean that other people won’t run into the same problem and go looking for an resolution. So having a resolution on record here is helpful.
