### ISSUE TITLE
non-document-error internal, ArrayIndexOutOfBoundsException with AMBIGUOUS_AMPERSAND

### ISSUE THREAD

**Issue by scop** [validator/validator#221]
The attached file, when fed to the validator over a POST request e.g. like:

```shell
$ curl --data-binary @vnu-bug.txt --header "Content-Type: text/html" http://localhost:8888/?out=gnu
[...]
: non-document-error internal: Oops. That was not supposed to happen. A bug manifested itself in the application internals. Unable to continue. Sorry. The admin was notified.
```
...causes this stack trace:

```
nu.validator.servlet.VerifierServletTransaction - RuntimeException, doc: null schema:  lax: false
java.lang.ArrayIndexOutOfBoundsException: -1
	at nu.validator.htmlparser.impl.ErrorReportingTokenizer.checkChar(ErrorReportingTokenizer.java:240)
	at nu.validator.htmlparser.impl.Tokenizer.stateLoop(Tokenizer.java:3232)
	at nu.validator.htmlparser.impl.Tokenizer.tokenizeBuffer(Tokenizer.java:1313)
	at nu.validator.htmlparser.io.Driver.runStates(Driver.java:320)
	at nu.validator.htmlparser.io.Driver.tokenize(Driver.java:219)
	at nu.validator.htmlparser.sax.HtmlParser.tokenize(HtmlParser.java:503)
	at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:423)
	at nu.validator.xml.WiretapXMLReaderWrapper.parse(WiretapXMLReaderWrapper.java:152)
	at nu.validator.xml.AttributesPermutingXMLReaderWrapper.parse(AttributesPermutingXMLReaderWrapper.java:285)
	at nu.validator.servlet.VerifierServletTransaction.validate(VerifierServletTransaction.java:983)
	at nu.validator.servlet.VerifierServletTransaction.service(VerifierServletTransaction.java:803)
	at nu.validator.servlet.VerifierServlet.doPost(VerifierServlet.java:271)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at nu.validator.servlet.MultipartFormDataFilter.doFilter(MultipartFormDataFilter.java:194)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at nu.validator.servlet.InboundGzipFilter.doFilter(InboundGzipFilter.java:57)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at nu.validator.servlet.InboundSizeLimitFilter.doFilter(InboundSizeLimitFilter.java:61)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

I tried to minimize the test case even more but did not succeed, it quite probably is quite sensitive to the length of something in it (like the ArrayIndexOutOfBoundsException kind of hints). This happens with the 1 January 2016 release as well as current git master.

[vnu-bug.txt](https://github.com/validator/validator/files/89063/vnu-bug.txt)

**Comment by sideshowbarker** [comment]
Thanks for catching this. It was a bad regression caused was a flub in the htmlparser changes I made recently to address issue #31 (and similar reports of the same issue).

I think I’ve finally got it right this time but I have found it challenging to fit this handling neatly into the relevant part of the existing htmlparser code, so it’s possible I’m still overlooking something and there may be other regressions waiting to be found.
