### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in vnu.jar

### ISSUE THREAD

**Issue by MacroMan** [validator/validator#240]
Checking certain HTML files gives me an java.lang.ArrayIndexOutOfBoundsException error.

A sample file that causes the error is attached

[vnu_java_error.txt](https://github.com/validator/validator/files/123331/vnu_java_error.txt)
[html-file.txt](https://github.com/validator/validator/files/123334/html-file.txt)

This error was generated using version 16.1.1 of vnu.jar downloaded from this github project.
Running on Ubuntu 14.04 x64 and JDK8

david@veriton:/tmp$ java -jar /var/www/zeus/validator/vnu.jar /tmp/validator-file.html
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at nu.validator.htmlparser.impl.ErrorReportingTokenizer.checkChar(ErrorReportingTokenizer.java:240)
	at nu.validator.htmlparser.impl.Tokenizer.stateLoop(Tokenizer.java:3232)
	at nu.validator.htmlparser.impl.Tokenizer.tokenizeBuffer(Tokenizer.java:1313)
	at nu.validator.htmlparser.io.Driver.runStates(Driver.java:320)
	at nu.validator.htmlparser.io.Driver.tokenize(Driver.java:219)
	at nu.validator.htmlparser.sax.HtmlParser.tokenize(HtmlParser.java:503)
	at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:423)
	at nu.validator.xml.WiretapXMLReaderWrapper.parse(WiretapXMLReaderWrapper.java:152)
	at nu.validator.validation.SimpleDocumentValidator.checkAsHTML(SimpleDocumentValidator.java:376)
	at nu.validator.validation.SimpleDocumentValidator.checkHtmlFile(SimpleDocumentValidator.java:332)
	at nu.validator.client.SimpleCommandLineValidator.checkHtmlFile(SimpleCommandLineValidator.java:275)
	at nu.validator.client.SimpleCommandLineValidator.checkFiles(SimpleCommandLineValidator.java:235)
	at nu.validator.client.SimpleCommandLineValidator.main(SimpleCommandLineValidator.java:180)

**Comment by sideshowbarker** [comment]
Please try that document again with the latest `vnu.jar` from https://sideshowbarker.net/nightlies/jar/

From the exception message and stack trace in your comment, the problem you’re seeing is almost certainly due to the same bug reported in #221 but that I subsequently fixed about three weeks ago.

So if you run `vnu.jar --version` and it says `16.1.15` or earlier (e.g. most likely `15.12.25`), then you definitely need to grab the latest from https://sideshowbarker.net/nightlies/jar/

**Comment by MacroMan** [comment]
Using the nightly version doesn't have this bug, so it was most likely the bug you fixed in #221 

Any chance you could add that link onto the vnu download page for others that encounter the safe issue?
