### ISSUE TITLE
WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Naveen701372** [validator/validator#242]
I'm installing nu-validator on windows 64-bit platform.
As soon as i ran this command it gave me this output.
```
D:\IOP\validator>python ./build/build.py all
Traceback (most recent call last):
  File "./build/build.py", line 73, in <module>
    validatorVersion = time.strftime('%y.%-m.%-e')
ValueError: Invalid format string

```

so i made following changes and it gor executed after that.

`validatorVersion = time.strftime('%y.%-m.%-e') to  validatorVersion = time.strftime('%d %B %Y')`

after some time i got this error

```
D:\IOP\validator>python ./build/build.py all
git submodule update --init
Submodule 'galimatias' (https://github.com/validator/galimatias.git) registered
for path 'galimatias'
Submodule 'htmlparser' (https://github.com/validator/htmlparser.git) registered
for path 'htmlparser'
Submodule 'jing-trang' (https://github.com/relaxng/jing-trang.git) registered fo
r path 'jing-trang'
Submodule 'tests' (https://github.com/validator/tests.git) registered for path '
tests'
Cloning into 'galimatias'...
remote: Counting objects: 2687, done.
remote: Total 2687 (delta 0), reused 0 (delta 0), pack-reused 2687
Receiving objects: 100% (2687/2687), 1016.76 KiB | 147.00 KiB/s, done.
Resolving deltas: 100% (1388/1388), done.
Checking connectivity... done.
Submodule path 'galimatias': checked out 'd111d6e6e70872f893b2f903c61577b28bb7d4
57'
Cloning into 'htmlparser'...
remote: Counting objects: 9174, done.
remote: Total 9174 (delta 0), reused 0 (delta 0), pack-reused 9174R
Receiving objects: 100% (9174/9174), 4.10 MiB | 373.00 KiB/s, done.
Resolving deltas:   0% (0/4290)
Resolving deltas: 100% (4290/4290), done.
Checking connectivity... done.
Submodule path 'htmlparser': checked out '0706524421fc046e113b4efadaba5c70584e07
06'
Cloning into 'jing-trang'...
remote: Counting objects: 24078, done.
remote: Total 24078 (delta 0), reused 0 (delta 0), pack-reused 24078
Receiving objects: 100% (24078/24078), 27.88 MiB | 414.00 KiB/s, done.
Resolving deltas: 100% (13166/13166), done.
Checking connectivity... done.
Submodule path 'jing-trang': checked out '35eb11b84a230ee4d7168f12f98a28bf40e940
aa'
Cloning into 'tests'...
remote: Counting objects: 6113, done.
rReceiving objects: 100% (6113/611emote: Total 6113 (delta 0), reused 0 (delta 0
), pack-reused 6113
Receiving objects: 100% (6113/6113), 1.02 MiB | 196.00 KiB/s, done.
Resolving deltas: 100% (3116/3116), done.
Checking connectivity... done.
Submodule path 'tests': checked out '942284e43bcb655db86ceba2e80a7dff36d457ca'
https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1.1/icu4j-54.1.1.jar
https://repo1.maven.org/maven2/com/shapesecurity/salvation/1.0.3/salvation-1.0.3
.jar
https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.
10.jar
https://repo1.maven.org/maven2/commons-fileupload/commons-fileupload/1.3.1/commo
ns-fileupload-1.3.1.jar
https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar
https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-loggi
ng-1.2.jar
https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-loggi
ng-1.2-adapters.jar
https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-loggi
ng-1.2-api.jar
https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servl
et-api-3.1.0.jar
https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar
https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar
https://repo1.maven.org/maven2/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.
0.jar
https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.4/httpclie
nt-4.4.jar
https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4/httpcore-4
.4.jar
https://repo1.maven.org/maven2/org/easytesting/fest-assert/1.4/fest-assert-1.4.j
ar
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/9.2.9.v20150224/jett
y-http-9.2.9.v20150224.jar
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/9.2.9.v20150224/jetty-
io-9.2.9.v20150224.jar
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/9.2.9.v20150224/
jetty-security-9.2.9.v20150224.jar
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/9.2.9.v20150224/je
tty-server-9.2.9.v20150224.jar
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/9.2.9.v20150224/j
etty-servlet-9.2.9.v20150224.jar
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlets/9.2.9.v20150224/
jetty-servlets-9.2.9.v20150224.jar
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/9.2.9.v20150224/jett
y-util-9.2.9.v20150224.jar
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/9.2.9.v20150224
/jetty-util-ajax-9.2.9.v20150224.jar
https://repo1.maven.org/maven2/org/hamcrest/hamcrest-api/1.0/hamcrest-api-1.0.ja
r
https://repo1.maven.org/maven2/org/mozilla/rhino/1.7R5/rhino-1.7R5.jar
https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.jar
https://repo1.maven.org/maven2/xom/xom/1.2.5/xom-1.2.5.jar
https://raw.githubusercontent.com/tabatkins/parse-css/a878df1503af3bfb63493a6368
5a117a24988959/parse-css.js
https://raw.githubusercontent.com/douglascrockford/JSON-js/3d7767b6b1f3da363c625
ff54e63bbf20e9e83ac/json.js
https://help.whatwg.org/extensions/a-rel/
https://help.whatwg.org/extensions/link-rel/
https://wiki.whatwg.org/wiki/MicrosyntaxDescriptions
https://www.iana.org/assignments/language-subtag-registry/language-subtag-regist
ry
https://wiki.whatwg.org/wiki/Validator.nu_alt_advice
.\ant
Traceback (most recent call last):
  File "./build/build.py", line 1503, in <module>
  File "./build/build.py", line 1231, in buildAll
  File "./build/build.py", line 648, in buildJing
  File "./build/build.py", line 217, in runCmd
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

So i changed my python27 version and installed python34-64bit.
which gave me following error

```
`C:\Users\NU00351442\Documents\interoperability\vnu.jar_16.1.1\validator>python .
/build/build.py all
git submodule update --init
Submodule 'galimatias' (https://github.com/validator/galimatias.git) registered
for path 'galimatias'
Submodule 'htmlparser' (https://github.com/validator/htmlparser.git) registered
for path 'htmlparser'
Submodule 'jing-trang' (https://github.com/relaxng/jing-trang.git) registered fo
r path 'jing-trang'
Submodule 'tests' (https://github.com/validator/tests.git) registered for path '
tests'
Cloning into 'galimatias'...
remote: Counting objects: 2687, done.
remote: Total 2687 (delta 0), reused 0 (delta 0), pack-reused 2687Receiving obje
cts:  98% (2634/2687), 932.01 KiB | 169.00 KiB/s
Receiving objects: 100% (2687/2687), 1016.76 KiB | 170.00 KiB/s, done.
Resolving deltas: 100% (1388/1388), done.
Checking connectivity... done.
Submodule path 'galimatias': checked out 'd111d6e6e70872f893b2f903c61577b28bb7d4
57'
Cloning into 'htmlparser'...
remote: Counting objects: 9174, done.
remote: Total 9174 (delta 0), reused 0 (delta 0), pack-reused 9174
Receiving objects: 100% (9174/9174), 4.10 MiB | 480.00 KiB/s, done.
Resolving deltas: 100% (4290/4290), done.
Checking connectivity... done.
Submodule path 'htmlparser': checked out '0706524421fc046e113b4efadaba5c70584e07
06'
Cloning into 'jing-trang'...
remote: Counting objects: 24078, done.
remote: Total 24078 (delta 0), reused 0 (delta 0), pack-reused 24078
Receiving objects: 100% (24078/24078), 27.88 MiB | 170.00 KiB/s, done.
Resolving deltas: 100% (13166/13166), done.
Checking connectivity... done.
Submodule path 'jing-trang': checked out '35eb11b84a230ee4d7168f12f98a28bf40e940
aa'
Cloning into 'tests'...
remote: Counting objects: 6113, done.
remote: Total 6113 (delta 0), reused 0 (delta 0), pack-reused 6113
Receiving objects: 100% (6113/6113), 1.02 MiB | 141.00 KiB/s, done.
Resolving deltas: 100% (3116/3116), done.
Checking connectivity... done.
Submodule path 'tests': checked out '942284e43bcb655db86ceba2e80a7dff36d457ca'
https://repo1.maven.org/maven2/com/ibm/icu/icu4j/54.1.1/icu4j-54.1.1.jar
https://repo1.maven.org/maven2/com/shapesecurity/salvation/1.0.3/salvation-1.0.3
.jar
Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1182, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 963, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 898, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 1279, in connect
    super().connect()
  File "C:\Python34\lib\http\client.py", line 871, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 498, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python34\lib\socket.py", line 537, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./build/build.py", line 1500, in <module>
    downloadDependencies()
  File "./build/build.py", line 1224, in downloadDependencies
    downloadDependency(url, md5sum)
  File "./build/build.py", line 1215, in downloadDependency
    fetchUrlTo(url, path, md5sum)
  File "./build/build.py", line 1084, in fetchUrlTo
    f = urlopen(url)
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 464, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 482, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 442, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python34\lib\urllib\request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>
`
```
Can you help me from here ?

**Comment by sideshowbarker** [comment]
I don’t have a Windows machine to test this on myself, so any resolution on it is going to depend on an assist from somebody with a Windows environment.

**Comment by cvrebert** [comment]
> `time.strftime('%y.%-m.%-e')`

Apparently dashes before `strftime` percent format specifiers is a glibc-ism which means not to zero-pad the field. Evidently Windows' libc doesn't support this feature.

**Comment by cvrebert** [comment]
As for the 2nd error, I think `buildJing()` needs to run `./ant.bat` instead of `./ant` on Windows, since `/jing-trang/ant` is a shell script which presumably won't work on Windows.
