### ISSUE TITLE
NullPointerException in VerifierServletTransaction.useXhtml5Schema

### ISSUE THREAD

**Issue by hsivonen** [validator/validator#339]
It seems that `useXhtml5Schema` gets called when `schemaUrls` is `null`. The was no URL logged with this stack.

```
java.lang.NullPointerException
        at nu.validator.servlet.VerifierServletTransaction.useXhtml5Schema(VerifierServletTransaction.java:895)
        at nu.validator.servlet.VerifierServletTransaction.setupXmlParser(VerifierServletTransaction.java:1553)
        at nu.validator.servlet.Html5ConformanceCheckerTransaction.loadDocAndSetupParser(Html5ConformanceCheckerTransaction.java:114)
        at nu.validator.servlet.VerifierServletTransaction.validate(VerifierServletTransaction.java:966)
        at nu.validator.servlet.PageEmitter.emit(PageEmitter.java:28)
        at nu.validator.servlet.VerifierServletTransaction.service(VerifierServletTransaction.java:808)
        at nu.validator.servlet.VerifierServlet.doPost(VerifierServlet.java:294)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at nu.validator.servlet.MultipartFormDataFilter.doFilter(MultipartFormDataFilter.java:185)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at nu.validator.servlet.InboundGzipFilter.doFilter(InboundGzipFilter.java:60)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at nu.validator.servlet.InboundSizeLimitFilter.doFilter(InboundSizeLimitFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hsivonen** [comment]
I think the right fix is `schemaUrls = "";` in `setup()` in `Html5ConformanceCheckerTransaction`. @sideshowbarker, does that seem right?

**Comment by hsivonen** [comment]
(The fix from the previous comment is live at Validator.nu.)

**Comment by sideshowbarker** [comment]
> I think the right fix is `schemaUrls = "";` in `setup()` in `Html5ConformanceCheckerTransaction`. @sideshowbarker, does that seem right?

Yes, would seem so
