### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by schliflo** [validator/validator#642]
It seems like the Docker image provided over at DockerHub is currently broken:
```
$ docker run -t --rm validator/validator java -jar /vnu.jar https://www.w3.org/
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at nu.validator.htmlparser.io.HtmlInputStreamReader.<init>(HtmlInputStreamReader.java:175)
	at nu.validator.htmlparser.io.Driver.tokenize(Driver.java:197)
	at nu.validator.htmlparser.sax.HtmlParser.tokenize(HtmlParser.java:488)
	at nu.validator.htmlparser.sax.HtmlParser.parse(HtmlParser.java:408)
	at nu.validator.spec.html5.Html5AttributeDatatypeBuilder.parseSyntaxDescriptions(Html5AttributeDatatypeBuilder.java:76)
	at nu.validator.messages.MessageEmitterAdapter.<clinit>(MessageEmitterAdapter.java:291)
	at nu.validator.client.SimpleCommandLineValidator.setErrorHandler(SimpleCommandLineValidator.java:536)
	at nu.validator.client.SimpleCommandLineValidator.setup(SimpleCommandLineValidator.java:302)
	at nu.validator.client.SimpleCommandLineValidator.main(SimpleCommandLineValidator.java:291)
```

Running the same thing with the older image tagged as travis-test - everything works as expected:
```
$ docker run -t --rm validator/validator:travis-test java -jar /vnu.jar https://www.w3.org/
"https://www.w3.org/":1.1-1.109: error: Obsolete doctype. Expected “<!DOCTYPE html>”.
"https://www.w3.org/":9.1-9.68: info warning:  The “type” attribute for the “style” element is not needed and should be omitted.
"https://www.w3.org/":608.1-608.56: info warning: The “type” attribute is unnecessary for JavaScript resources.
```

**Comment by sideshowbarker** [comment]
Yeah, the cause of this is the same as for issue #634. I’m working on a fix.

**Comment by sideshowbarker** [comment]
The latest image from DockerHub should fix this problem. If it doesn’t, lemme know

**Comment by schliflo** [comment]
i can confirm that the latest build works now. thank you.

**Comment by sideshowbarker** [comment]
Cheers—thanks for having caught this and taken time to report it
